In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
%matplotlib inline
import sklearn

In [2]:
crm = pd.read_excel('dflp_case_sample_data.xlsx' , sheet_name='dflp_case_sample_data')
crm['label'] = crm['label'].astype(np.int64)

In [3]:
crm_features = crm[['days_last_order' , 'total_orders' , 'unique_days_visited' , 'total_sessions' , 'label']]
crm_features

,days_last_order,total_orders,unique_days_visited,total_sessions,label
0,5,34,130,404,0
1,7,3,17,24,1
2,14,13,58,101,0
3,22,15,94,177,0
4,19,13,101,198,0
5,7,19,20,95,0
6,3,7,74,173,0
7,6,5,47,65,0
8,5,6,16,42,0
9,3,6,15,16,0
10,27,5,65,129,1
11,25,13,1,1,1
12,12,6,84,128,1
13,8,4,28,34,1
14,1,31,143,452,0
15,30,4,9,12,1
16,19,14,2,2,1
17,1,8,43,59,0
18,30,4,18,27,1
19,4,4,3,8,0
20,20,3,8,36,1
21,18,6,123,437,0
22,19,4,9,17,1
23,7,23,139,498,1
24,6,9,65,113,0
25,2,3,67,124,1
26,5,80,64,178,0
27,5,24,99,174,0
28,1,16,78,227,0
29,0,4,6,11,1
...,...,...,...,...,...
4777,11,22,153,807,0
4778,20,5,64,204,0
4779,12,6,68,113,0
4780,20,4,13,21,1
4781,2,5,4,10,0
4782,3,14,65,186,0
4783,12,3,5,11,0
4784,11,13,50,113,0
4785,2,7,53,126,0
4786,7,7,71,174,0
4787,6,36,59,195,0
4788,13,9,33,50,0
4789,14,15,90,267,0
4790,16,9,2,2,0
4791,7,12,123,308,0
4792,12,13,60,141,1
4793,0,9,46,137,0
4794,0,19,24,112,0
4795,14,132,142,362,0
4796,15,5,125,326,0
4797,16,24,166,652,0
4798,12,5,83,197,0
4799,8,5,50,75,1
4800,7,15,61,162,0
4801,1,4,13,14,1
4802,16,8,11,12,0
4803,12,19,83,141,0
4804,4,54,118,690,0
4805,11,4,21,36,1
4806,18,4,81,198,0

In [4]:
#X = crm_features[['total_orders', 'total_sessions']]
#X = crm_features.drop('label', axis=1)
#y = crm_features.label
y = crm['label']
X = crm[['unique_days_visited' , 'total_sessions']]

In [5]:
from sklearn.model_selection import train_test_split

In [51]:
X_train,X_valid,y_train,y_valid = train_test_split(X, y, random_state = 101, stratify=y, test_size=0.25)

In [52]:
y_train.value_counts(normalize=True)

0    0.800832
1    0.199168
Name: label, dtype: float64

In [53]:
y_valid.value_counts(normalize=True)

0    0.800333
1    0.199667
Name: label, dtype: float64

In [54]:
X_train.shape, y_train.shape

((3605, 2), (3605,))

In [55]:
X_valid.shape, y_valid.shape

((1202, 2), (1202,))

In [56]:
from sklearn.tree import DecisionTreeClassifier

In [57]:
from sklearn.tree import DecisionTreeRegressor

In [58]:
dt_model = DecisionTreeClassifier(random_state=10)

In [59]:
dt_model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=10,
            splitter='best')

In [60]:
dt_model.score(X_train, y_train)

0.9323162274618585

In [61]:
dt_model.score(X_valid, y_valid)

0.7154742096505824

In [62]:
predictions = dt_model.predict(X_valid)

In [64]:
predictions1 = pd.DataFrame(predictions)

In [50]:
pe = pd.DataFrame(predictions, columns=['pred'])
#est_set = pd.concat([df1, df4], axis=1, join="inner")
result = pd.concat([X_valid, y_valid], axis=1, join="inner")
#esult = pd.concat([df1, df4], axis=1, join="inner")
result = result.reset_index()
result1 = pd.concat([result , pe], axis=1 , join="inner")
result1

     index  unique_days_visited  total_sessions  label  pred
0     2893                   38             167      0     0
1      890                   82             169      0     0
2     1976                   20              60      0     0
3      768                    8              21      0     1
4     3799                    4               5      0     0
5      863                   40              99      0     0
6      205                   36              67      0     0
7     1288                   26              47      1     0
8      471                   40             139      0     0
9     2918                   58              98      0     0
10     905                   87             276      0     0
11    2471                   21              34      0     0
12    3755                   12              15      0     0
13    3201                   68             132      0     0
14    2527                    8               8      0     0
15    3666                   40              91      0     0
16    2921                    1               1      0     0
17    2211                   44              72      0     0
18    4374                   24              35      1     0
19     880                  123             228      0     0
20     509                    8              17      0     0
21     761                   84             184      0     0
22    1325                   35              65      0     0
23    3803                   40              72      0     0
24    2774                   69             133      0     0
25    4686                   35              61      1     0
26     444                   13              28      0     0
27    3626                   14              30      1     0
28    1222                  136             495      0     0
29    2107                  128             297      0     0
..     ...                  ...             ...    ...   ...
932   2338                   16              37      0     1
933     79                   35              41      0     0
934   3144                  103             273      0     0
935   1358                   40             201      0     1
936   2478                   20              45      1     0
937   1967                   82             314      0     0
938   3374                   14              29      1     0
939   3643                   67             119      0     0
940   3549                   96             311      0     0
941   2247                   89             166      0     0
942   3470                   58             120      1     0
943   3273                   21              33      0     0
944   3187                   31              50      0     1
945    928                   31              45      0     0
946   1560                   74             136      0     0
947   4730                   84             121      0     0
948   1939                  100             265      0     0
949   1400                   76             155      0     0
950   3198                   91             189      0     0
951   4099                   11              22      1     0
952   2638                   47             205      0     0
953   2952                   35              50      0     0
954    207                   91             172      0     0
955   3620                   38              55      1     0
956   1136                   28              45      0     0
957   3662                   56              88      0     0
958   2121                   26              57      1     1
959   1983                   25              42      0     0
960   2729                    6               8      0     0
961   2480                    9              19      0     0

[962 rows x 5 columns]

In [65]:
from sklearn.metrics import confusion_matrix

In [66]:
confusion_matrix(y_valid, predictions)

array([[813, 149],
       [193,  47]], dtype=int64)

In [67]:
from sklearn.metrics import accuracy_score

In [69]:
accuracy_score(y_valid, predictions)

0.7154742096505824